[package]
name = "relay_integrity"
version = "0.5.0-beta"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "relay_integrity"

[dependencies]
hdi = { workspace = true }

serde = { workspace = true }
